# Generated by Django 3.0.1 on 2020-01-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateTimeField(verbose_name='Date de naissance')),
                ('date_arrivee', models.DateTimeField(auto_now_add=True, verbose_name='Date de première arrivée')),
            ],
        ),
    ]
