# Generated by Django 3.0.1 on 2020-01-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('mail', models.CharField(max_length=200, null=True, verbose_name='Adresse mail')),
                ('adresse', models.CharField(max_length=500, null=True)),
                ('telephone', models.CharField(max_length=15, null=True, verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'arrivée")),
                ('date_depart', models.DateTimeField(null=True, verbose_name='Date de départ')),
                ('cage', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=30, null=True, verbose_name='Cage fournie')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Montant à payer')),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Montant restant à payer')),
            ],
        ),
        migrations.CreateModel(
            name='VisiteMedicale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de la visite')),
                ('type_visite', models.CharField(choices=[('VAC', 'Vaccination'), ('STE', 'Stérilisation'), ('CHECK', 'Checkup'), ('AUTRE', 'Autre')], max_length=30, null=True, verbose_name='Objet de la visite')),
                ('commentaire', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='date_adoption',
            field=models.DateTimeField(null=True, verbose_name="Date d'adoption"),
        ),
        migrations.AddField(
            model_name='animal',
            name='date_visite',
            field=models.DateTimeField(null=True, verbose_name='Date de prochaine visite vétérinaire'),
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='origine',
            field=models.CharField(choices=[('PENSION', 'Pension'), ('REFUGE', 'Refuge')], max_length=30, null=True, verbose_name='Origine'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexe',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=30, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sterilise',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=30, null=True, verbose_name='Stérilisé'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type_animal',
            field=models.CharField(choices=[('LAPIN', 'Lapin'), ('HAMSTER', 'Hamster'), ('COCHON_DINDE', "Cochon d'inde")], max_length=30, null=True, verbose_name="Type d'animal"),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccine',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=30, null=True, verbose_name='Vacciné'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_arrivee',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de première arrivée'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_naissance',
            field=models.DateTimeField(null=True, verbose_name='Date de naissance'),
        ),
    ]
