# Generated by Django 3.0.1 on 2020-01-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTest', '0002_auto_20200119_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicationTest.Proprietaire'),
        ),
    ]
