# Generated by Django 3.0.1 on 2020-02-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTest', '0004_auto_20200202_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='sejour',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicationTest.Animal'),
        ),
        migrations.AddField(
            model_name='visitemedicale',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicationTest.Animal'),
        ),
    ]
