# Generated by Django 3.0.1 on 2020-02-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTest', '0005_auto_20200202_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_arrivee',
            field=models.DateTimeField(null=True, verbose_name='Date de première arrivée'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='origine',
            field=models.CharField(choices=[('PENSION', 'Pension'), ('REFUGE', 'Refuge'), ('', '')], max_length=30, null=True, verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexe',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=30, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_animal',
            field=models.CharField(choices=[('LAPIN', 'Lapin'), ('HAMSTER', 'Hamster'), ('COCHON_DINDE', "Cochon d'inde"), ('', '')], max_length=30, verbose_name="Type d'animal"),
        ),
        migrations.AlterField(
            model_name='visitemedicale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de la visite'),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name="Date de l'adoption")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Montant à payer')),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Montant restant à payer')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicationTest.Proprietaire')),
            ],
        ),
    ]
