# Generated by Django 3.0.1 on 2020-02-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTest', '0006_auto_20200216_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicationTest.Adoption'),
        ),
    ]
