# Generated by Django 3.0.1 on 2020-02-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationTest', '0007_animal_adoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='proprietaire',
        ),
    ]
